image: ruby:2.5.3

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/ruby
    - node_modules

stages:
  - test
  - lint

before_script:
  - apt-get update && apt-get install -y cmake
  - gem install bundler  --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor

tests:
  stage: test
  allow_failure: false
  script:
    - bundle exec rake test

lint:
  stage: lint
  allow_failure: false
  script:
    - bundle exec rubocop
